### ISSUE TITLE
error classification

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#41] opened 2021-01-17 09:51 UTC
Hi,

This is a suggestion for enhancement for better error reporting.

Currently, a number of the error thrown are from a generic Error class (if I'm not wrong), so something like

```
Error: Property name is required, Property model is required

Error: document not found
```

I'm thinking if these can be better classified and throw things like

```
ValidationError: Property name is required, Property model is required

DocumentNotFoundError: document not found
```

There could be others, or better naming, but a little more specific than throwing generic Error class

Thanks

**Comment by AV25242** [comment] 2021-01-18 22:58
Node.js errors were not exported, an [issue](https://github.com/couchbaselabs/node-ottoman/issues/356) has been created

**Comment by AV25242** [comment] 2021-02-08 23:47
aplha.16 should address this

**Comment by bwgjoseph** [comment] 2021-02-09 15:14
Hi,

This wasn't address in alpha.16

I'm still getting this error message, without the error type (It is still Error instead of ValidationError)

```
1) test create function
       ottoman - should create new doc:
     Error: Property callsign is required, Property name is required, Property model is required
      at Object.validate (node_modules\ottoman\src\schema\helpers\fn-schema.ts:170:11)
      at Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\ottoman\src\model\utils\store-life-cycle.ts:17:14
      at Generator.next (<anonymous>)
      at fulfilled (node_modules\ottoman\lib\model\utils\store-life-cycle.js:5:58)
```

**Comment by AV25242** [comment] 2021-02-09 19:16
@bwgjoseph  sorry for the confusion this will be fixed with a new issue that will be created later

**Comment by httpJunkie** [comment] 2021-02-19 20:57
Just an update Joseph, this issue and a lot of the others we spoke about will be released in alpha.18 most likely on Monday. Also, Arun has not been available to respond to some issues and probably other things because he lives in Texas and has been without power for several days because of a snowstorm. He should return back next week. We are making progress on these issues but have decided not to release the alpha today in hopes to get more closed Pull Requests added to the release.

**Comment by bwgjoseph** [comment] 2021-02-20 06:54
Sure, as we discussed before, we want to have better (quality) release rather than rush into releases. So do what you and your team needs to before the release. I can continue with other test in the mean time.

Oh no, I hope everything will be better for @AV25242, and I'm glad to see that he replied earlier on too! Take care!

**Comment by bwgjoseph** [comment] 2021-02-26 07:08
@AV25242 

As you mentioned earlier that your team is still trying to see if there is any place that does not report the error correctly. When I'm using `findById`, it is still reporting `Error: document not found` 

![image](https://user-images.githubusercontent.com/37484538/109267339-5d199900-7844-11eb-8307-f2a7dd9d6374.png)

Hope it helps

**Comment by bwgjoseph** [comment] 2021-03-23 16:51
What is the error type being returned?

For example, I have a model that uses `minLength` and this test purposely fail it

```js
try {
    await Airplane.create({ ...hawkAirplane, email: 'a' });
} catch (error) {
    console.log(error);
    console.log(error.name);
    console.log(error.message);
    console.log(Object.keys(error));
}
```

I'm getting this output

```js
ValidationError: Property 'email' is shorter than the minimum allowed length '5'
    at Object.validate (Z:\mongoose-vs-ottoman\node_modules\ottoman\src\schema\helpers\fn-schema.ts:167:11)
    at Z:\mongoose-vs-ottoman\node_modules\ottoman\src\model\utils\store-life-cycle.ts:17:14
    at Generator.next (<anonymous>)
    at fulfilled (Z:\mongoose-vs-ottoman\node_modules\ottoman\lib\model\utils\store-life-cycle.js:5:58)
ValidationError
Property 'email' is shorter than the minimum allowed length '5'
[ 'name' ]
```

I'm blindly guessing what's the return type of the error right now

---

And the previous comment about the `findById` returned error is still not correct

**Comment by bwgjoseph** [comment] 2021-03-23 17:00
Also, the format of the error message seem to differ by quite a bit

For `minLength, maxLength`, it is showing something like `Property 'email' is shorter than the minimum allowed length '5'`

For `min, max`, it is showing as `-1 is less than 0`. Should it be something similar to the above?

**Comment by bwgjoseph** [comment] 2021-03-23 17:07
Seem like using `updateById` throws a different type of error, and not exactly matching as well.

```js
await Airplane.updateById('nosuchid', { callsign: 'abc' });

// error
DocumentNotFoundError: document not found
    at _getWrappedErr (Z:\Development\workspace\github\bwgjoseph\mongoose-vs-ottoman\node_modules\couchbase\lib\errors.js:856:14)
    at Object.wrapLcbErr (Z:\Development\workspace\github\bwgjoseph\mongoose-vs-ottoman\node_modules\couchbase\lib\errors.js:1009:20)
    at Z:\Development\workspace\github\bwgjoseph\mongoose-vs-ottoman\node_modules\couchbase\lib\collection.js:237:24 {
  cause: LibcouchbaseError { code: 301 },
  context: KeyValueErrorContext {
    status_code: 1,
    opaque: 2,
    cas: CbCas { '0': <Buffer 00 00 00 00 00 00 00 00> },
    key: 'Airplane::nosuchid',
    bucket: 'testBucket',
    collection: '_default',
    scope: '_default',
    context: '',
    ref: ''
  }
}

// error.name, above shows DocumentNotFoundError
Error

// error.message
document not found
```

**Comment by AV25242** [comment] 2021-03-23 17:42
@bwgjoseph  this is a known issue and I think we should address this separately. The issue is in the underlying Nodejs SDK.
This ticket although Intended to solve issues like this has already uncovered many such exceptions that were not bubbling up. 
Document Not Found is missed out in the underlying SDK in few instance and hence you see this. I would label it as a low priority and stick it on a separate ticket. Do you concur ?

**Comment by bwgjoseph** [comment] 2021-03-23 18:12
@AV25242 do see the last 3 comments. For the `DocumentNotFoundError`, I'm alright if you classify this as the SDK issue but for the other two comments, I don't think it has to do with the SDK.

In short, what is the error object type? and the inconsistency of the error message

https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/41#issuecomment-805062190
https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/41#issuecomment-805068972

**Comment by AV25242** [comment] 2021-03-23 19:06
Ah ! yeah totally agree, I think i left it out, let me reach out to the team to get an answer. So what you essentially mean here is
a) On a create when the constraints fails it does not return back Validation Error Type ?
b) Consistency of Error message needs some attention ?

**Comment by AV25242** [comment] 2021-03-24 19:15
created an issue https://github.com/couchbaselabs/node-ottoman/issues/423

**Comment by AV25242** [comment] 2021-04-02 20:25
Checkout the new alpha.21 release and let us know.

**Comment by bwgjoseph** [comment] 2021-04-03 07:00
This is generally ok, but a very small difference in the message.

```js
// for min/max length
// note the quote at the value 5
Property 'email' is shorter than the minimum allowed length '5'

// for min/max
// note the lack of quote at the value 0
Property 'capacity' is less than the minimum allowed value 0
```

Should this be consistent as well? And for value, should it be '.... value **of** X?

**Comment by AV25242** [comment] 2021-04-03 16:19
I agree with you

**Comment by AV25242** [comment] 2021-04-03 16:31
will re-open internal ticket

**Comment by AV25242** [comment] 2021-04-16 15:54
check out alpha.22

**Closed** 2021-04-16 16:59 UTC
Labels: await-verification
